# Generated by Django 4.2.3 on 2024-07-13 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_management_app', '0001_added_users_and_servers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
