# Generated by Django 4.2.3 on 2024-07-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_management_app', '0002_alter_servers_name_alter_users_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='dbms',
            field=models.CharField(choices=[('MySQL', 'MySQL'), ('TBD', 'To Be Determined')], default='TBD', max_length=100),
        ),
    ]
