# Generated by Django 4.2.3 on 2024-07-14 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server_management_app', '0003_servers_dbms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_name', models.CharField(max_length=100, unique=True)),
                ('container_hash', models.CharField(max_length=12)),
                ('created', models.CharField()),
                ('status', models.CharField()),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database_name', models.CharField()),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_management_app.containers')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100, unique=True)),
                ('tag', models.CharField()),
                ('image_hash', models.CharField(max_length=12)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='user_name',
        ),
        migrations.DeleteModel(
            name='Servers',
        ),
        migrations.AddField(
            model_name='containers',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_management_app.images'),
        ),
        migrations.AddField(
            model_name='container_users',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_management_app.containers'),
        ),
        migrations.AddField(
            model_name='container_users',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server_management_app.users'),
        ),
    ]
