version: '3.8'

services:
  my-postgres:
    image: postgres:15
    container_name: my-postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./custom_pg_hba.conf:/custom_pg_hba.conf
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    entrypoint: [ "/docker-entrypoint-initdb.d/entrypoint.sh" ]

  web:
    build: .
    container_name: django
    ports:
      - '8000:8000'
    volumes:
      - .:/app
      - django_ssh_keys:/root/.ssh
    environment:
      - DJANGO_ENV=${DJANGO_ENV}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      - my-postgres

volumes:
  pg_data:
  django_ssh_keys:
